Add Skills & Projects buttons
Agilefreaks/FreaksCatalog-iOS pull request #16
Opened 2021-07-22 13:35 UTC by DejanuTeodora

## Description
Added "skills" and "projects" buttons under the navigation bar

## Related
https://trello.com/c/Ysmth1uO

## Documentation

## Link to demo

## Steps to Test or Reproduce

1. Install app
2. Open app

2021-07-22 13:41 UTC, vladstanescu94 requested changes

2021-07-22 13:41 UTC, vladstanescu94 commented on Shared/Features/Freaks/View/FreaksView.swift
> +                HStack {
Can we extract this Hstack into a separate component?

2021-07-22 13:41 UTC, vladstanescu94 commented on Shared/Features/Freaks/View/FreaksView.swift
> +                    Spacer()
Also, can we have some kind of divider between the Skills button and the Projects button?

2021-07-22 13:42 UTC, DejanuTeodora commented
![](https://github.trello.services/images/mini-trello-icon.png) [iOS - Setup UI for skills and projects on Freaks Screen](https://trello.com/c/Ysmth1uO/67-ios-setup-ui-for-skills-and-projects-on-freaks-screen)

2021-07-22 13:57 UTC, MihaiPantiru requested changes

2021-07-22 13:57 UTC, MihaiPantiru commented on Shared/Features/Freaks/View/FreaksView.swift
> +                .frame(height: 60)
Applying this setup here, I think the buttons are very small, even the background color is correct. We should make sure the buttons are half the screen and 60 pixels in height. 
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-22 at 16 55 10](https://user-images.githubusercontent.com/481425/126651122-adce3d17-6d8a-419b-8d6b-7655bc02f17e.png).

2021-07-22 14:01 UTC, MihaiPantiru commented on Shared/Features/Freaks/View/FreaksView.swift
> +                .frame(height: 60)
https://www.hackingwithswift.com/quick-start/swiftui/how-to-provide-relative-sizes-using-geometryreader - I think using GeometryReader may help

2021-07-22 15:55 UTC, vladstanescu94 approved these changes

2021-07-22 16:08 UTC, MihaiPantiru requested changes

2021-07-22 16:08 UTC, MihaiPantiru commented on Shared/Features/Freaks/View/FreaksButtonsView.swift
> +struct FreaksButtonsView: View {
I think a better name would be FilterButtonsView. In this way, we have more context about what these buttons are for.

2021-07-22 16:08 UTC, MihaiPantiru commented on Shared/Features/Freaks/View/FreaksButtonsView.swift
> +        .foregroundColor(.white)
Instead of `.white` let's use `SecondaryColor`. This will help us a lot if we will change the app theme colors later.

2021-07-22 16:08 UTC, MihaiPantiru commented on Shared/Features/Freaks/View/FreaksView.swift
> +                List(viewModel.freaks, id: \.firstName) { freak in
A new line between the VStack components will make the code easier to read.

2021-07-23 08:44 UTC, MihaiPantiru approved these changes

2021-07-23 08:44 UTC, merged