Present Freaks list as a grid
Agilefreaks/FreaksCatalog-iOS pull request #20
Opened 2021-07-23 12:04 UTC by DejanuTeodora

## Description
On Freaks screen we use a grid to present the list of users.

## Related
https://trello.com/c/8sB6g96C

## Documentation
https://www.hackingwithswift.com/quick-start/swiftui/how-to-render-a-gradient
https://designcode.io/swiftui-handbook-mask-and-transparency

## Link to demo

## Steps to Test or Reproduce

1. Install app
2. Open app

2021-07-23 12:08 UTC, DejanuTeodora commented
![](https://github.trello.services/images/mini-trello-icon.png) [iOS - Freaks Screen - Present Freaks list as a grid](https://trello.com/c/8sB6g96C/71-ios-freaks-screen-present-freaks-list-as-a-grid)

2021-07-23 13:01 UTC, vladstanescu94 requested changes

2021-07-26 08:35 UTC, vladstanescu94 approved these changes

2021-07-26 08:40 UTC, rmoldo approved these changes

2021-07-26 08:40 UTC, merged