Feature/details screen
Agilefreaks/FreaksCatalog-iOS pull request #26
Opened 2021-07-27 12:03 UTC by DejanuTeodora

## Description
Added description, skills, projects, level on details screen

## Related
https://trello.com/c/WO0QNiyJ

## Documentation

## Link to demo

## Steps to Test or Reproduce

1. Install app
2. Open app
3. Tap on freak

2021-07-27 12:04 UTC, DejanuTeodora commented
![](https://github.trello.services/images/mini-trello-icon.png) [iOS - Details Screen - Setup UI](https://trello.com/c/WO0QNiyJ/85-ios-details-screen-setup-ui)

2021-07-27 12:32 UTC, vladstanescu94 requested changes
Also, use the spacing and the sizes from the design if possible.

2021-07-27 12:32 UTC, vladstanescu94 commented on Shared/Features/FreakDetails/View/FreakDetailsView.swift
> +    // let freak = Bundle.main.decode([Freak].self, from: "MockData.json")
Remove comments, please

2021-07-27 12:32 UTC, vladstanescu94 commented on Shared/Features/FreakDetails/View/FreakDetailsView.swift
> +                    .padding()
We need to make the text elements full width, to consider the case where we have fewer words on the description. Don't rely on the content to layout the view.

2021-07-27 12:32 UTC, vladstanescu94 commented on Shared/Features/FreakDetails/View/FreakDetailsView.swift
> +            .previewInterfaceOrientation(.portraitUpsideDown)
Remove this preview orientation

2021-07-28 06:29 UTC, vladstanescu94 approved these changes

2021-07-28 06:43 UTC, rmoldo approved these changes

2021-07-28 06:48 UTC, merged