Implement skills screen
Agilefreaks/FreaksCatalog-iOS pull request #27
Opened 2021-07-27 12:53 UTC by rmoldo

## Description
Implemented skills screen 

## Related
https://trello.com/c/RUBqr0dj

## Documentation

## Link to demo
https://imgur.com/YrcKCJg

## Steps to Test or Reproduce
1. Install app
2. Open app
3. Tap on skills button

2021-07-27 12:56 UTC, rmoldo commented
![](https://github.trello.services/images/mini-trello-icon.png) [iOS - setup Filter Screen UI](https://trello.com/c/RUBqr0dj/97-ios-setup-filter-screen-ui)

2021-07-28 06:33 UTC, vladstanescu94 requested changes

2021-07-28 06:33 UTC, vladstanescu94 commented on Shared/Features/Freaks/View/SkillsView.swift
> +//
Remove file headers.

2021-07-28 06:37 UTC, vladstanescu94 approved these changes

2021-07-28 06:44 UTC, DejanuTeodora approved these changes

2021-07-28 06:58 UTC, merged

2021-07-30 08:02 UTC, craciungabi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a freak](https://trello.com/c/fkhC8ev3/90-add-a-freak)