Add logic to filter Freaks
Agilefreaks/FreaksCatalog-iOS pull request #30
Opened 2021-08-03 10:27 UTC by DejanuTeodora

## Description
Added logic to filter freaks by skills.

## Related
https://trello.com/c/9v3osWKH

## Documentation

## Link to demo

## Steps to Test or Reproduce
1. Install app
2. Open app
3. Tap on skills button 
4. Select skills
5. Tap on apply button

2021-08-03 10:27 UTC, DejanuTeodora commented
![](https://github.trello.services/images/mini-trello-icon.png) [iOS - Skills Filter Screen - Add Apply Button](https://trello.com/c/9v3osWKH/106-ios-skills-filter-screen-add-apply-button)

2021-08-03 11:13 UTC, vladstanescu94 requested changes

2021-08-03 11:13 UTC, vladstanescu94 commented on Shared/Features/Freaks/View/SkillsView.swift
> +                    self.viewModel.isFilterApplied = true
We also need to reset isFilterApplied somewhere.

2021-08-03 11:13 UTC, vladstanescu94 commented on Shared/Features/Freaks/ViewModel/FreaksViewModel.swift
> +import UIKit
Why are we importing UIKit here?

2021-08-03 12:29 UTC, vladstanescu94 commented on Shared/Features/Freaks/View/SkillsView.swift
> +                viewModel.isFilterApplied = false
Now we are resetting this var if we tap on the Reset button, but what happens if we just close the sheet or press the X button?

2021-08-04 07:49 UTC, vladstanescu94 approved these changes

2021-08-04 07:57 UTC, RalucaMihaela approved these changes

2021-08-04 08:01 UTC, merged