Add tabbar navigation
Agilefreaks/FreaksCatalog-iOS pull request #32
Opened 2021-08-10 06:56 UTC by DejanuTeodora

## Description
Added tab bar navigation

## Related
https://trello.com/c/Dz5zbLDN

## Documentation
https://www.hackingwithswift.com/quick-start/swiftui/adding-tabview-and-tabitem

## Link to demo

## Steps to Test or Reproduce

1. Install app
2. Open app
3. Tap one of the tab bar elements

2021-08-10 06:57 UTC, DejanuTeodora commented
![](https://github.trello.services/images/mini-trello-icon.png) [iOS - Add tabbar navigation](https://trello.com/c/Dz5zbLDN/160-ios-add-tabbar-navigation)

2021-08-10 07:01 UTC, vladstanescu94 approved these changes

2021-08-10 07:04 UTC, vladstanescu94 requested changes

2021-08-10 07:04 UTC, vladstanescu94 commented on Shared/Features/Freaks/View/HomeView.swift
> +struct HomeView: View {
We need to move this file to another directory.

2021-08-10 07:04 UTC, vladstanescu94 commented on Shared/Features/Freaks/View/MainView.swift
> +
We need to move this file to another directory.

2021-08-10 07:04 UTC, vladstanescu94 commented on Shared/Features/Freaks/View/ProjectsView.swift
> +
We need to move this file to another directory.

2021-08-10 08:31 UTC, MihaiPantiru approved these changes

2021-08-10 08:32 UTC, vladstanescu94 approved these changes

2021-08-10 08:34 UTC, merged

2021-08-11 09:09 UTC, cipry13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Android - Freaks Screen - get and show freaks from API](https://trello.com/c/8YqKWs3B/154-android-freaks-screen-get-and-show-freaks-from-api)